In [2]:
from utils.data_prepare import load_text
train_list = load_text('./data/process/train.txt')

In [11]:
print(train_list[:500])

[23, 24, 140, 1208, 1619, 1215, 333, 594, 805, 78, 161, 644, 152, 214, 10, 103]	3
[566, 381, 516, 675, 648, 292, 2, 127, 333, 1397, 177, 60, 43, 96, 373, 546, 231]	6
[132, 580, 445, 160, 60, 173, 217, 191, 632, 484, 497, 136, 715, 307, 2, 39, 20, 39, 426, 292, 1282, 61, 64, 68, 754]	10
[432, 83, 306, 653, 272, 760, 13, 191, 1683, 536, 34, 482, 221, 156, 8, 451, 136, 338, 478]	6
[84, 165, 309, 45, 50, 59, 1032, 134, 439, 2, 650, 10, 182, 56, 29, 239, 1397, 61, 438, 10, 3, 115]	3
[156, 89, 234, 25


In [7]:
for line in train_list.split('\n')[:5]:
    ids, label = line.split('\t')
    ids = eval(ids)
    label = eval(label)
    print(ids, label)
    print(type(ids), type(label))

[23, 24, 140, 1208, 1619, 1215, 333, 594, 805, 78, 161, 644, 152, 214, 10, 103] 3
<class 'list'> <class 'int'>
[566, 381, 516, 675, 648, 292, 2, 127, 333, 1397, 177, 60, 43, 96, 373, 546, 231] 6
<class 'list'> <class 'int'>
[132, 580, 445, 160, 60, 173, 217, 191, 632, 484, 497, 136, 715, 307, 2, 39, 20, 39, 426, 292, 1282, 61, 64, 68, 754] 10
<class 'list'> <class 'int'>
[432, 83, 306, 653, 272, 760, 13, 191, 1683, 536, 34, 482, 221, 156, 8, 451, 136, 338, 478] 6
<class 'list'> <class 'int'>
[84, 165, 309, 45, 50, 59, 1032, 134, 439, 2, 650, 10, 182, 56, 29, 239, 1397, 61, 438, 10, 3, 115] 3
<class 'list'> <class 'int'>


In [12]:
from utils.dataset import NewsDataset, collate_fn
from torch.utils.data import DataLoader
train_dataset = NewsDataset("./data/process/train.txt")
val_dataset = NewsDataset("./data/process/val.txt")
batch_size = 64
train_loader = DataLoader(train_dataset, batch_size=batch_size, collate_fn=collate_fn, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, collate_fn=collate_fn, shuffle=False)

In [13]:
print('=============train_loader =============')
for data, label in train_loader:
    print(data)
    print(data.shape)
    print(label)
    print(label.shape)
    break

=============train_loader =============
tensor([[ 644,  239,    7,  ...,    1,    1,    1],
        [ 354,  115,  167,  ...,    1,    1,    1],
        [ 437,  165,  212,  ...,    1,    1,    1],
        ...,
        [1724, 2095,  828,  ...,    1,    1,    1],
        [ 575, 1473,  691,  ...,    1,    1,    1],
        [ 172,   87,   18,  ...,    1,    1,    1]])
torch.Size([64, 32])
tensor([13,  3,  3,  9, 13,  0,  7,  6,  5, 10,  6, 10, 12,  9, 10,  8, 13,  4,
        10,  9,  9,  7, 13,  3,  6,  9,  6,  7,  6,  9, 13,  6,  8,  9,  0, 10,
         7, 10, 10,  6,  6,  4, 10,  0, 10,  6, 10, 13,  8,  3,  5,  3,  4,  3,
         3, 10,  9, 10,  8, 10, 10,  5,  3,  3])
torch.Size([64])


In [14]:
print('=============val_loader =============')
for data, label in val_loader:
    print(data)
    print(data.shape)
    print(label)
    print(label.shape)
    break

=============val_loader =============
tensor([[ 176,  157,  262,  ...,    1,    1,    1],
        [ 396,  785,  404,  ...,    1,    1,    1],
        [  53,   49, 1295,  ...,    1,    1,    1],
        ...,
        [ 284,  513,  290,  ...,    1,    1,    1],
        [  15,    8,  102,  ...,    1,    1,    1],
        [  52,  255,  912,  ...,    1,    1,    1]])
torch.Size([64, 32])
tensor([ 3,  3,  7,  3,  9,  9, 13, 10,  3,  3,  5,  4, 10, 10,  0, 10,  6, 13,
         6, 10,  3,  6,  9,  9,  6,  3, 13,  5,  6, 10,  9,  0,  8,  6, 13,  3,
        13, 13, 10,  9,  5,  3,  3,  6,  6, 10,  2, 10,  3,  3, 10,  6, 10, 10,
        10,  6, 12,  3,  3,  7,  6,  2,  4,  3])
torch.Size([64])


In [16]:
from utils.tokenizer import Vocabulary

vocab = Vocabulary.load('./data/process/vocab.txt')

In [18]:
data[0]

tensor([176, 157, 262,  42, 175,  10, 103,   2,  88, 635,  74,  34, 614, 236,
        214, 169,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1])

In [21]:
" ".join(vocab.to_tokens(data[3].tolist()))

'江 西 铜 业 涨 3 . 3 3 %   高 盛 升 评 级 至 中 性 <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad>'